# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 839776d94721e2c01d0d6035d610d36a8ca47a22611c827f4f208a3d07e5ce2b893598aa17675a413a9748848882b4ce5deb855d59b0c37e525cf0b31097b330

test:
  secret_key_base: 3f60bba35451e3427d9fac96c6c46a26d75e6fab5fae2932d92d230b2cc64f6e3d56bd20fa8fcb477ef7cd8f4e24f63bfcfb1902870d26e32608299ba9311298

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
